name: Windows CI

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: cmd
      run: .\src\scripts\build_ci.bat
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: friction-ci-${{github.sha}}-windows-x64
        path: build\output\*.7z
